Store/StoreApp/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StoreApp.Entities.Models;
using StoreApp.Services.Contracts;

namespace StoreApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IServiceManager _serviceManager;
        private readonly Cart _cart;

        public OrderController(IServiceManager serviceManager, Cart cart)
        {
            _serviceManager = serviceManager;
            _cart = cart;
        }
        [Authorize]
        public ViewResult CheckOut() => View(new Order());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CheckOut([FromForm] Order order)
        {
            if (_cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty.");
            }
            if (ModelState.IsValid)
            {
                order.Lines = _cart.Lines.ToArray();
                _serviceManager.OrderService.SaveOrder(order);
                _cart.Clear();
                return RedirectToPage("/Complete", new { OrderIds = order.OrderID });
            }
            else
            {
                return View();
            }
        }

    }
}

Store/StoreApp/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using StoreApp.Entities.Models;
using StoreApp.Infrastructure.Extensions;
using StoreApp.Services.Contracts;

namespace StoreApp.Pages
{
    public class CartModel : PageModel
    {
        private readonly IServiceManager _manager;

        public Cart Cart { get; set; }

        public CartModel(IServiceManager manager, Cart cartService)
        {
            _manager = manager;
            Cart = cartService;
        }

        public string ReturnUrl { get; set; } = "/";
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int productID, string returnUrl)
        {
            Product? product = _manager.ProductService.GetOneProduct(productID, false);
            if (product != null)
            {
                Cart.AddItem(product, 1);
            }
            return RedirectToPage(new { returnUrl = returnUrl });
        }
        public IActionResult OnPostRemove(int id, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(x => x.Product.ProductID == id).Product);
            return Page();
        }

    }
}

Store/StoreApp/Pages/Complete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StoreApp.Pages
{
    public class CompleteModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Store/StoreApp/Pages/Contact.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StoreApp.Pages
{
    public class ContactModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Store/StoreApp/Pages/Demo.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StoreApp.Pages
{
    public class DemoModel : PageModel
    {
        public String? FullName => HttpContext?.Session?.GetString("name") ?? "Noname";

        public void OnGet()
        {
        }
        public void OnPost([FromForm] string name)
        {
            HttpContext.Session.SetString("name", name);
        }
    }
}

Store/StoreApp/Pages/Cart.cshtml
@page "/cart"

@model CartModel

Cart(@Model.Cart.Lines.Count())

<div>
    <div class="text-center display-6">Cart</div>
    <table >
        <thead>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Cart?.Lines ?? Enumerable.Empty<CartLine>())
            {
                <tr>
                    <td>@item.Product.ProductName</td>
                    <td>@item.Quantity</td>
                    <td>@item.Product.Price.ToString("c")</td>
                    <td>@((item.Product.Price * item.Quantity).ToString("c2"))</td>
                    <td>
                        <form method="post" asp-page-handler="Remove">
                            <input type="hidden" name="id" value="@item.Product.ProductID" />
                            <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                            <button type="submit" class="btn btn-sm btn-danger">
                                <i class="fa fa-trash"></i>
                                Remove
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total :</td>
                <td colspan="3" class="text-right text-danger">@Model.Cart?.ComputeTotalValue().ToString("c2")</td>
            </tr>
        </tfoot>
    </table>
    <div class="text-center my-3">
        <div class="btn-group">
            <a class="btn btn-primary" href="@Model?.ReturnUrl">Continue Shopping</a>
            <a class="btn btn-primary mx-2" asp-action="Checkout" asp-controller="Order">Checkout</a>
        </div>
    </div>
</div>

Store/StoreApp/Pages/Complete.cshtml
@page

<div class="text-center">
    <h6 class="display-6">Thanks</h6>
    <p>Thanks a for placing order #@OrderId</p>
    <p>We'll ship yout goods as soon as possible.</p>
    <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Return to Store</a>
</div>

@functions {

    [BindProperty(SupportsGet = true)]

    public String? OrderId { get; set; }
}

Store/StoreApp/Pages/Contact.cshtml
@page "/getintouch"

<div class="text-center my-5 ">
    <div class="display-6 border-bottom">Contact</div>
    <div class="lead mt-5">
        <i class="fa fa-phone bg-secondary text-white p-3  rounded-5 my-3"></i>
        <p>
            ALO 120 BTK Akademi bilgi ve destek hattı
        </p>
        <i class="fa-solid fa-address-book bg-secondary text-white p-3  rounded-5 my-3"></i>
        <p>
            Bilgi Teknolojileri ve İletişim Kurumu Eskişehir Yolu 10.Km
            No: 276 Posta Kodu: 06530 Çankaya/Ankara
        </p>

        <i class="fa-solid fa-envelope bg-secondary text-white p-3  rounded-5 my-3"></i>
        <p>
            destek@btkakademi.gov.tr
        </p>
    </div>
</div>

Store/StoreApp/Pages/Demo.cshtml
@page
@model StoreApp.Pages.DemoModel
@{
}
<div class="my-5 text-center">
    <div class="display-6">Hello @Model?.FullName</div>
    <form method="post" asp-page="/demo">
        <div class="form-group">
            <input class="form-control" name="name" placeholder="Enter Your Name" />
            <input type="submit" class="btn btn-primary my-3" />
        </div>
    </form>
</div>